# Generated by Django 4.2.21 on 2025-05-19 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing_comment_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="creator",
            new_name="owner",
        ),
    ]
